stages:
  - build
  - deploy
  - build-production
  - deploy-production

variables:
  DOCKER_IMAGE: "frontend-simpeg:latest"
  CONTAINER_NAME: "frontend-simpeg"
  PORT: "3001"

build:
  stage: build
  tags:
    - simpeg-frontend
  script:
    - echo "🚀 Building Docker Image"
    - docker compose -f docker-compose.dev.yml build
  only:
    - develop

deploy:
  stage: deploy
  tags:
    - simpeg-frontend
  script:
    - echo "🚀 Stopping and removing existing containers"
    - docker compose -f docker-compose.dev.yml down || true
    - echo "🚀 Starting container with Docker Compose"
    - docker compose -f docker-compose.dev.yml up -d
  only:
    - develop

# Production
build-production:
  stage: build
  tags:
    - frontend-production
  script:
    - echo "🚀 Building Docker Image (Production)"
    - docker compose -f docker-compose.yml build
  only:
    - production

deploy-production:
  stage: deploy
  tags:
    - frontend-production
  script:
    - echo "🚀 Stopping and removing existing containers (Production)"
    - docker compose -f docker-compose.yml down || true
    - echo "🚀 Starting container with Docker Compose (Production)"
    - docker compose -f docker-compose.yml up -d
  only:
    - production
