version: "3.8"

services:
  react-app:
    image: ${CI_REGISTRY_IMAGE:-simpeg-frontend}:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://api-simpeg.zmidevelopment.com/api/simpeg
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=local
      - VITE_API_URL=https://api-simpeg.zmidevelopment.com/api/simpeg
    env_file:
      - .env
    restart: unless-stopped
