version: "3.8"

services:
  react-app:
    image: ${CI_REGISTRY_IMAGE:-your-app-image}:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    # env_file:
    #   - .env
    restart: unless-stopped
